

<!DOCTYPE html>
<!--[if IE 8]><html class="no-js lt-ie9" lang="en" > <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en" > <!--<![endif]-->
<head>
  <meta charset="utf-8">
  
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  
  <title>Friendly tracebacks - in English &mdash; Friendly tracebacks 0.0.28a documentation</title>
  

  
  
  
  

  
  <script type="text/javascript" src="_static/js/modernizr.min.js"></script>
  
    
      <script type="text/javascript" id="documentation_options" data-url_root="./" src="_static/documentation_options.js"></script>
        <script type="text/javascript" src="_static/jquery.js"></script>
        <script type="text/javascript" src="_static/underscore.js"></script>
        <script type="text/javascript" src="_static/doctools.js"></script>
        <script type="text/javascript" src="_static/language_data.js"></script>
    
    <script type="text/javascript" src="_static/js/theme.js"></script>

    

  
  <link rel="stylesheet" href="_static/css/theme.css" type="text/css" />
  <link rel="stylesheet" href="_static/pygments.css" type="text/css" />
  <link rel="stylesheet" href="_static/custom.css" type="text/css" />
    <link rel="index" title="Index" href="genindex.html" />
    <link rel="search" title="Search" href="search.html" />
    <link rel="next" title="Friendly SyntaxError tracebacks - in English" href="syntax_tracebacks_en_3.6.html" />
    <link rel="prev" title="Comparison between Python versions" href="compare.html" /> 
</head>

<body class="wy-body-for-nav">

   
  <div class="wy-grid-for-nav">
    
    <nav data-toggle="wy-nav-shift" class="wy-nav-side">
      <div class="wy-side-scroll">
        <div class="wy-side-nav-search" >
          

          
            <a href="index.html" class="icon icon-home"> Friendly tracebacks
          

          
          </a>

          
            
            
              <div class="version">
                0.0.28a
              </div>
            
          

          
<div role="search">
  <form id="rtd-search-form" class="wy-form" action="search.html" method="get">
    <input type="text" name="q" placeholder="Search docs" />
    <input type="hidden" name="check_keywords" value="yes" />
    <input type="hidden" name="area" value="default" />
  </form>
</div>

          
        </div>

        <div class="wy-menu wy-menu-vertical" data-spy="affix" role="navigation" aria-label="main navigation">
          
            
            
              
            
            
              <p class="caption"><span class="caption-text">About</span></p>
<ul>
<li class="toctree-l1"><a class="reference internal" href="usage.html">Usage</a></li>
<li class="toctree-l1"><a class="reference internal" href="mu_thonny.html">About Mu and Thonny</a></li>
<li class="toctree-l1"><a class="reference internal" href="mu.html">Using with Mu</a></li>
<li class="toctree-l1"><a class="reference internal" href="thonny.html">Using with Thonny</a></li>
<li class="toctree-l1"><a class="reference internal" href="design.html">Some thoughts on the design of friendly-traceback</a></li>
</ul>
<p class="caption"><span class="caption-text">Known exceptions (Python 3.8)</span></p>
<ul>
<li class="toctree-l1"><a class="reference internal" href="known.html">Known exceptions</a></li>
<li class="toctree-l1"><a class="reference internal" href="tracebacks_en_3.8.html">Friendly tracebacks - in English</a></li>
<li class="toctree-l1"><a class="reference internal" href="syntax_tracebacks_en_3.8.html">Friendly SyntaxError tracebacks - in English</a></li>
</ul>
<p class="caption"><span class="caption-text">Contribute</span></p>
<ul>
<li class="toctree-l1"><a class="reference internal" href="suggest.html">Suggest an addition</a></li>
<li class="toctree-l1"><a class="reference internal" href="adding_exception.html">Developer: Add a new Exception case</a></li>
<li class="toctree-l1"><a class="reference internal" href="syntax_error.html">Developer: Add a new SyntaxError case</a></li>
</ul>
<p class="caption"><span class="caption-text">Use in your project</span></p>
<ul>
<li class="toctree-l1"><a class="reference internal" href="custom.html">Description of demos</a></li>
<li class="toctree-l1"><a class="reference internal" href="api.html">Public API</a></li>
<li class="toctree-l1"><a class="reference internal" href="graph.html">Project files</a></li>
<li class="toctree-l1"><a class="reference internal" href="lies.html">Intentional lies</a></li>
<li class="toctree-l1"><a class="reference internal" href="translation_notes.html">Notes on translations - using gettext</a></li>
</ul>
<p class="caption"><span class="caption-text">Other versions and languages</span></p>
<ul class="current">
<li class="toctree-l1"><a class="reference internal" href="compare.html">Comparison between Python versions</a></li>
<li class="toctree-l1 current"><a class="current reference internal" href="#">Friendly tracebacks - Python 3.6 in English</a><ul>
<li class="toctree-l2"><a class="reference internal" href="#arithmeticerror">ArithmeticError</a></li>
<li class="toctree-l2"><a class="reference internal" href="#filenotfounderror">FileNotFoundError</a></li>
<li class="toctree-l2"><a class="reference internal" href="#importerror">ImportError</a></li>
<li class="toctree-l2"><a class="reference internal" href="#keyerror">KeyError</a></li>
<li class="toctree-l2"><a class="reference internal" href="#lookuperror">LookupError</a></li>
<li class="toctree-l2"><a class="reference internal" href="#indexerror-short-tuple">IndexError - short tuple</a></li>
<li class="toctree-l2"><a class="reference internal" href="#indexerror-long-list">IndexError - long list</a></li>
<li class="toctree-l2"><a class="reference internal" href="#modulenotfounderror">ModuleNotFoundError</a></li>
<li class="toctree-l2"><a class="reference internal" href="#nameerror">NameError</a></li>
<li class="toctree-l2"><a class="reference internal" href="#overflowerror">OverflowError</a></li>
<li class="toctree-l2"><a class="reference internal" href="#typeerror-1-concatenate-two-different-types">TypeError - 1: concatenate two different types</a></li>
<li class="toctree-l2"><a class="reference internal" href="#typeerror-1a-concatenate-two-different-types">TypeError - 1a: concatenate two different types</a></li>
<li class="toctree-l2"><a class="reference internal" href="#typeerror-1b-concatenate-two-different-types">TypeError - 1b: concatenate two different types</a></li>
<li class="toctree-l2"><a class="reference internal" href="#typeerror-2-unsupported-operand-type-s-for">TypeError - 2: unsupported operand type(s) for +</a></li>
<li class="toctree-l2"><a class="reference internal" href="#typeerror-2a-unsupported-operand-type-s-for">TypeError - 2a: unsupported operand type(s) for +=</a></li>
<li class="toctree-l2"><a class="reference internal" href="#typeerror-3-unsupported-operand-type-s-for">TypeError - 3: unsupported operand type(s) for -</a></li>
<li class="toctree-l2"><a class="reference internal" href="#typeerror-3a-unsupported-operand-type-s-for">TypeError - 3a: unsupported operand type(s) for -=</a></li>
<li class="toctree-l2"><a class="reference internal" href="#typeerror-4-unsupported-operand-type-s-for">TypeError - 4: unsupported operand type(s) for *</a></li>
<li class="toctree-l2"><a class="reference internal" href="#typeerror-4a-unsupported-operand-type-s-for">TypeError - 4a: unsupported operand type(s) for <code class="docutils literal notranslate"><span class="pre">*=</span></code></a></li>
<li class="toctree-l2"><a class="reference internal" href="#typeerror-5-unsupported-operand-type-s-for">TypeError - 5: unsupported operand type(s) for /</a></li>
<li class="toctree-l2"><a class="reference internal" href="#typeerror-5a-unsupported-operand-type-s-for">TypeError - 5a: unsupported operand type(s) for /=</a></li>
<li class="toctree-l2"><a class="reference internal" href="#typeerror-5b-unsupported-operand-type-s-for">TypeError - 5b: unsupported operand type(s) for //</a></li>
<li class="toctree-l2"><a class="reference internal" href="#typeerror-5c-unsupported-operand-type-s-for">TypeError - 5c: unsupported operand type(s) for //=</a></li>
<li class="toctree-l2"><a class="reference internal" href="#typeerror-6-unsupported-operand-type-s-for">TypeError - 6: unsupported operand type(s) for &amp;</a></li>
<li class="toctree-l2"><a class="reference internal" href="#typeerror-6a-unsupported-operand-type-s-for">TypeError - 6a: unsupported operand type(s) for &amp;=</a></li>
<li class="toctree-l2"><a class="reference internal" href="#typeerror-7-unsupported-operand-type-s-for">TypeError - 7: unsupported operand type(s) for **</a></li>
<li class="toctree-l2"><a class="reference internal" href="#typeerror-7a-unsupported-operand-type-s-for">TypeError - 7a: unsupported operand type(s) for <code class="docutils literal notranslate"><span class="pre">**=</span></code></a></li>
<li class="toctree-l2"><a class="reference internal" href="#typeerror-8-unsupported-operand-type-s-for">TypeError - 8: unsupported operand type(s) for &gt;&gt;</a></li>
<li class="toctree-l2"><a class="reference internal" href="#typeerror-8a-unsupported-operand-type-s-for">TypeError - 8a: unsupported operand type(s) for &gt;&gt;=</a></li>
<li class="toctree-l2"><a class="reference internal" href="#typeerror-9-unsupported-operand-type-s-for">TypeError - 9: unsupported operand type(s) for &#64;</a></li>
<li class="toctree-l2"><a class="reference internal" href="#typeerror-9a-unsupported-operand-type-s-for">TypeError - 9a: unsupported operand type(s) for &#64;=</a></li>
<li class="toctree-l2"><a class="reference internal" href="#typeerror-10-comparison-between-incompatible-types">TypeError - 10: comparison between incompatible types</a></li>
<li class="toctree-l2"><a class="reference internal" href="#typeerror-11-bad-operand-type-for-unary">TypeError - 11: bad operand type for unary +</a></li>
<li class="toctree-l2"><a class="reference internal" href="#typeerror-11a-bad-operand-type-for-unary">TypeError - 11a: bad operand type for unary -</a></li>
<li class="toctree-l2"><a class="reference internal" href="#typeerror-11b-bad-operand-type-for-unary">TypeError - 11b: bad operand type for unary ~</a></li>
<li class="toctree-l2"><a class="reference internal" href="#typeerror-12-object-does-not-support-item-assignment">TypeError - 12: object does not support item assignment</a></li>
<li class="toctree-l2"><a class="reference internal" href="#typeerror-13-wrong-number-of-positional-arguments">TypeError - 13: wrong number of positional arguments</a></li>
<li class="toctree-l2"><a class="reference internal" href="#typeerror-14-missing-positional-arguments">TypeError - 14: missing positional arguments</a></li>
<li class="toctree-l2"><a class="reference internal" href="#typeerror-15-tuple-object-is-not-callable">TypeError - 15: tuple object is not callable</a></li>
<li class="toctree-l2"><a class="reference internal" href="#typeerror-15a-list-object-is-not-callable">TypeError - 15a: list object is not callable</a></li>
<li class="toctree-l2"><a class="reference internal" href="#unboundlocalerror">UnboundLocalError</a></li>
<li class="toctree-l2"><a class="reference internal" href="#unknown-exception">Unknown exception</a></li>
<li class="toctree-l2"><a class="reference internal" href="#zerodivisionerror-1">ZeroDivisionError - 1</a></li>
<li class="toctree-l2"><a class="reference internal" href="#zerodivisionerror-2">ZeroDivisionError - 2</a></li>
</ul>
</li>
<li class="toctree-l1"><a class="reference internal" href="syntax_tracebacks_en_3.6.html">SyntaxError - Python 3.6 in English</a></li>
<li class="toctree-l1"><a class="reference internal" href="tracebacks_en_3.7.html">Friendly tracebacks - Python 3.7 in English</a></li>
<li class="toctree-l1"><a class="reference internal" href="syntax_tracebacks_en_3.7.html">SyntaxError - Python 3.7 in English</a></li>
<li class="toctree-l1"><a class="reference internal" href="tracebacks_fr.html">Friendly tracebacks - en Français</a></li>
<li class="toctree-l1"><a class="reference internal" href="syntax_tracebacks_fr.html">Friendly SyntaxError tracebacks - en Français</a></li>
</ul>
<p class="caption"><span class="caption-text">varia</span></p>
<ul>
<li class="toctree-l1"><a class="reference internal" href="changelog.html">Change Log</a></li>
</ul>

            
          
        </div>
      </div>
    </nav>

    <section data-toggle="wy-nav-shift" class="wy-nav-content-wrap">

      
      <nav class="wy-nav-top" aria-label="top navigation">
        
          <i data-toggle="wy-nav-top" class="fa fa-bars"></i>
          <a href="index.html">Friendly tracebacks</a>
        
      </nav>


      <div class="wy-nav-content">
        
        <div class="rst-content style-external-links">
        
          















<div role="navigation" aria-label="breadcrumbs navigation">

  <ul class="wy-breadcrumbs">
    
      <li><a href="index.html">Docs</a> &raquo;</li>
        
      <li>Friendly tracebacks - in English</li>
    
    
      <li class="wy-breadcrumbs-aside">
        
            
            <a href="_sources/tracebacks_en_3.6.rst.txt" rel="nofollow"> View page source</a>
          
        
      </li>
    
  </ul>

  
  <div class="rst-breadcrumbs-buttons" role="navigation" aria-label="breadcrumb navigation">
      
        <a href="syntax_tracebacks_en_3.6.html" class="btn btn-neutral float-right" title="Friendly SyntaxError tracebacks - in English" accesskey="n">Next <span class="fa fa-arrow-circle-right"></span></a>
      
      
        <a href="compare.html" class="btn btn-neutral float-left" title="Comparison between Python versions" accesskey="p"><span class="fa fa-arrow-circle-left"></span> Previous</a>
      
  </div>
  
  <hr/>
</div>
          <div role="main" class="document" itemscope="itemscope" itemtype="http://schema.org/Article">
           <div itemprop="articleBody">
            
  <div class="section" id="friendly-tracebacks-in-english">
<h1>Friendly tracebacks - in English<a class="headerlink" href="#friendly-tracebacks-in-english" title="Permalink to this headline">¶</a></h1>
<p>Friendly-traceback aims to provide friendlier feedback when an exception
is raised than what is done by Python.
Below, we can find some examples. SyntaxError cases, as well as TabError and
IndentationError cases, are shown in a separate page.
Ideally, an example of each case handled by friendly-traceback
should be included here.</p>
<div class="admonition note">
<p class="admonition-title">Note</p>
<p>The content of this page is generated by running
trb_english.py located in the <code class="docutils literal notranslate"><span class="pre">tests/</span></code> directory.
This needs to be done explicitly, independently of updating the
documentation using Sphinx.
On Windows, if Sphinx is installed on your computer, it is suggested
instead to run make_trb.bat in the root directory as it will create
similar files for all languages <em>and</em> update the documentation.</p>
</div>
<p>Friendly-traceback version: 0.0.28a
Python version: 3.6.8</p>
<div class="section" id="arithmeticerror">
<h2>ArithmeticError<a class="headerlink" href="#arithmeticerror" title="Permalink to this headline">¶</a></h2>
<div class="highlight-none notranslate"><div class="highlight"><pre><span></span>Python exception:
    ArithmeticError:

ArithmeticError is the base class for those built-in exceptions
that are raised for various arithmetic errors.
It is unusual that you are seeing this exception;
normally, a more specific exception should have been raised.

Execution stopped on line 9 of file &#39;TESTS:\except\test_arithmetic_error.py&#39;.

    7:         # Usually, a subclass such as ZeroDivisionError, etc., would
    8:         # likely be raised.
--&gt; 9:         raise ArithmeticError
</pre></div>
</div>
</div>
<div class="section" id="filenotfounderror">
<h2>FileNotFoundError<a class="headerlink" href="#filenotfounderror" title="Permalink to this headline">¶</a></h2>
<div class="highlight-none notranslate"><div class="highlight"><pre><span></span>Python exception:
    FileNotFoundError: [Errno 2] No such file or directory: &#39;does_not_exist&#39;

A FileNotFoundError exception indicates that you
are trying to open a file that cannot be found by Python.
This could be because you misspelled the name of the file.

Likely cause based on the information given by Python:
    In your program, the name of the
    file that cannot be found is &#39;does_not_exist&#39;.

Execution stopped on line 6 of file &#39;TESTS:\except\test_file_not_found_error.py&#39;.

   4: def test_file_not_found_error():
   5:     try:
--&gt;6:         open(&quot;does_not_exist&quot;)
</pre></div>
</div>
</div>
<div class="section" id="importerror">
<h2>ImportError<a class="headerlink" href="#importerror" title="Permalink to this headline">¶</a></h2>
<div class="highlight-none notranslate"><div class="highlight"><pre><span></span>Python exception:
    ImportError: cannot import name &#39;Pi&#39;

This exception indicates that a certain object could not
be imported from a module or package. Most often, this is
because the name of the object is not spelled correctly.

Likely cause based on the information given by Python:
    The object that could not be imported is &#39;Pi&#39;.

Execution stopped on line 6 of file &#39;TESTS:\except\test_import_error.py&#39;.

   4: def test_import_error():
   5:     try:
--&gt;6:         from math import Pi
</pre></div>
</div>
</div>
<div class="section" id="keyerror">
<h2>KeyError<a class="headerlink" href="#keyerror" title="Permalink to this headline">¶</a></h2>
<div class="highlight-none notranslate"><div class="highlight"><pre><span></span>Python exception:
    KeyError: &#39;c&#39;

A KeyError is raised when a value is not found as a
key in a Python dict.

Likely cause based on the information given by Python:
    In your program, the name of the key
    that cannot be found is &#39;c&#39;.

Execution stopped on line 7 of file &#39;TESTS:\except\test_key_error.py&#39;.

   5:     d = {&quot;a&quot;: 1, &quot;b&quot;: 2}
   6:     try:
--&gt;7:         d[&quot;c&quot;]

d: {&#39;a&#39;: 1, &#39;b&#39;: 2}
</pre></div>
</div>
</div>
<div class="section" id="lookuperror">
<h2>LookupError<a class="headerlink" href="#lookuperror" title="Permalink to this headline">¶</a></h2>
<div class="highlight-none notranslate"><div class="highlight"><pre><span></span>Python exception:
    LookupError:

LookupError is the base class for the exceptions that are raised
when a key or index used on a mapping or sequence is invalid.
It can also be raised directly by codecs.lookup().

Execution stopped on line 10 of file &#39;TESTS:\except\test_lookup_error.py&#39;.

    8:         # other than possibly codecs.lookup(), which is why we raise
    9:         # it directly here for our example.
--&gt;10:         raise LookupError
</pre></div>
</div>
</div>
<div class="section" id="indexerror-short-tuple">
<h2>IndexError - short tuple<a class="headerlink" href="#indexerror-short-tuple" title="Permalink to this headline">¶</a></h2>
<div class="highlight-none notranslate"><div class="highlight"><pre><span></span>Python exception:
    IndexError: tuple index out of range

An IndexError occurs when you are try to get an item from a list,
a tuple, or a similar object (sequence), by using an index which
does not exists; typically, this is because the index you give
is greater than the length of the sequence.
Reminder: the first item of a sequence is at index 0.

Likely cause based on the information given by Python:
    In this case, the sequence is a tuple.

Execution stopped on line 8 of file &#39;TESTS:\except\test_index_error.py&#39;.

    6:     b = [1, 2, 3]
    7:     try:
--&gt; 8:         print(a[3], b[2])

a: (1, 2, 3)
b: [1, 2, 3]
</pre></div>
</div>
</div>
<div class="section" id="indexerror-long-list">
<h2>IndexError - long list<a class="headerlink" href="#indexerror-long-list" title="Permalink to this headline">¶</a></h2>
<div class="highlight-none notranslate"><div class="highlight"><pre><span></span>Python exception:
    IndexError: list index out of range

An IndexError occurs when you are try to get an item from a list,
a tuple, or a similar object (sequence), by using an index which
does not exists; typically, this is because the index you give
is greater than the length of the sequence.
Reminder: the first item of a sequence is at index 0.

Likely cause based on the information given by Python:
    In this case, the sequence is a list.

Execution stopped on line 22 of file &#39;TESTS:\except\test_index_error.py&#39;.

   20:     b = tuple(range(50))
   21:     try:
--&gt;22:         print(a[50], b[0])

a: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13...]  | len(a): 40
b: (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13...)  | len(b): 50
</pre></div>
</div>
</div>
<div class="section" id="modulenotfounderror">
<h2>ModuleNotFoundError<a class="headerlink" href="#modulenotfounderror" title="Permalink to this headline">¶</a></h2>
<div class="highlight-none notranslate"><div class="highlight"><pre><span></span>Python exception:
    ModuleNotFoundError: No module named &#39;does_not_exist&#39;

A ModuleNotFoundError exception indicates that you
are trying to import a module that cannot be found by Python.
This could be because you misspelled the name of the module
or because it is not installed on your computer.

Likely cause based on the information given by Python:
    In your program, the name of the
    module that cannot be found is &#39;does_not_exist&#39;.

Execution stopped on line 6 of file &#39;TESTS:\except\test_module_not_found_error.py&#39;.

   4: def test_module_not_found_error():
   5:     try:
--&gt;6:         import does_not_exist
</pre></div>
</div>
</div>
<div class="section" id="nameerror">
<h2>NameError<a class="headerlink" href="#nameerror" title="Permalink to this headline">¶</a></h2>
<div class="highlight-none notranslate"><div class="highlight"><pre><span></span>Python exception:
    NameError: name &#39;c&#39; is not defined

A NameError exception indicates that a variable or
function name is not known to Python.
Most often, this is because there is a spelling mistake.
However, sometimes it is because the name is used
before being defined or given a value.

Likely cause based on the information given by Python:
    In your program, the unknown name is &#39;c&#39;.

Execution stopped on line 6 of file &#39;TESTS:\except\test_name_error.py&#39;.

   4: def test_name_error():
   5:     try:
--&gt;6:         b = c
</pre></div>
</div>
</div>
<div class="section" id="overflowerror">
<h2>OverflowError<a class="headerlink" href="#overflowerror" title="Permalink to this headline">¶</a></h2>
<div class="highlight-none notranslate"><div class="highlight"><pre><span></span>Python exception:
    OverflowError: (34, &#39;Result too large&#39;)

An OverflowError is raised when the result of an arithmetic operation
is too large to be handled by the computer&#39;s processor.

Execution stopped on line 6 of file &#39;TESTS:\except\test_overflow_error.py&#39;.

   4: def test_overflow_error():
   5:     try:
--&gt;6:         2.0 ** 1600
</pre></div>
</div>
</div>
<div class="section" id="typeerror-1-concatenate-two-different-types">
<h2>TypeError - 1: concatenate two different types<a class="headerlink" href="#typeerror-1-concatenate-two-different-types" title="Permalink to this headline">¶</a></h2>
<div class="highlight-none notranslate"><div class="highlight"><pre><span></span>Python exception:
    TypeError: must be str, not int

A TypeError is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by tring to do an operation not allowed on a given type of object.

Likely cause based on the information given by Python:
    You tried to concatenate (add) two different types of objects:
    a string (&#39;str&#39;) and an integer (&#39;int&#39;)

Execution stopped on line 8 of file &#39;TESTS:\except\test_type_error.py&#39;.

    6:         a = &quot;a&quot;
    7:         one = 1
--&gt; 8:         result = a + one

a: &#39;a&#39;
one: 1
</pre></div>
</div>
</div>
<div class="section" id="typeerror-1a-concatenate-two-different-types">
<h2>TypeError - 1a: concatenate two different types<a class="headerlink" href="#typeerror-1a-concatenate-two-different-types" title="Permalink to this headline">¶</a></h2>
<div class="highlight-none notranslate"><div class="highlight"><pre><span></span>Python exception:
    TypeError: must be str, not list

A TypeError is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by tring to do an operation not allowed on a given type of object.

Likely cause based on the information given by Python:
    You tried to concatenate (add) two different types of objects:
    a string (&#39;str&#39;) and a list

Execution stopped on line 24 of file &#39;TESTS:\except\test_type_error.py&#39;.

   22:         a = &quot;a&quot;
   23:         a_list = [1, 2, 3]
--&gt;24:         result = a + a_list

a: &#39;a&#39;
a_list: [1, 2, 3]
</pre></div>
</div>
</div>
<div class="section" id="typeerror-1b-concatenate-two-different-types">
<h2>TypeError - 1b: concatenate two different types<a class="headerlink" href="#typeerror-1b-concatenate-two-different-types" title="Permalink to this headline">¶</a></h2>
<div class="highlight-none notranslate"><div class="highlight"><pre><span></span>Python exception:
    TypeError: can only concatenate tuple (not &quot;list&quot;) to tuple

A TypeError is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by tring to do an operation not allowed on a given type of object.

Likely cause based on the information given by Python:
    You tried to concatenate (add) two different types of objects:
    a tuple and a list

Execution stopped on line 40 of file &#39;TESTS:\except\test_type_error.py&#39;.

   38:         a_tuple = (1, 2, 3)
   39:         a_list = [1, 2, 3]
--&gt;40:         result = a_tuple + a_list

a_tuple: (1, 2, 3)
a_list: [1, 2, 3]
</pre></div>
</div>
</div>
<div class="section" id="typeerror-2-unsupported-operand-type-s-for">
<h2>TypeError - 2: unsupported operand type(s) for +<a class="headerlink" href="#typeerror-2-unsupported-operand-type-s-for" title="Permalink to this headline">¶</a></h2>
<div class="highlight-none notranslate"><div class="highlight"><pre><span></span>Python exception:
    TypeError: unsupported operand type(s) for +: &#39;int&#39; and &#39;NoneType&#39;

A TypeError is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by tring to do an operation not allowed on a given type of object.

Likely cause based on the information given by Python:
    You tried to add two incompatible types of objects:
    an integer (&#39;int&#39;) and a variable equal to None (&#39;NoneType&#39;)

Execution stopped on line 54 of file &#39;TESTS:\except\test_type_error.py&#39;.

   52:         one = 1
   53:         none = None
--&gt;54:         result = one + none

one: 1
none: None
</pre></div>
</div>
</div>
<div class="section" id="typeerror-2a-unsupported-operand-type-s-for">
<h2>TypeError - 2a: unsupported operand type(s) for +=<a class="headerlink" href="#typeerror-2a-unsupported-operand-type-s-for" title="Permalink to this headline">¶</a></h2>
<div class="highlight-none notranslate"><div class="highlight"><pre><span></span>Python exception:
    TypeError: unsupported operand type(s) for +=: &#39;int&#39; and &#39;str&#39;

A TypeError is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by tring to do an operation not allowed on a given type of object.

Likely cause based on the information given by Python:
    You tried to add two incompatible types of objects:
    an integer (&#39;int&#39;) and a string (&#39;str&#39;)

Execution stopped on line 68 of file &#39;TESTS:\except\test_type_error.py&#39;.

   66:         one = 1
   67:         two = &quot;two&quot;
--&gt;68:         one += two

one: 1
two: &#39;two&#39;
</pre></div>
</div>
</div>
<div class="section" id="typeerror-3-unsupported-operand-type-s-for">
<h2>TypeError - 3: unsupported operand type(s) for -<a class="headerlink" href="#typeerror-3-unsupported-operand-type-s-for" title="Permalink to this headline">¶</a></h2>
<div class="highlight-none notranslate"><div class="highlight"><pre><span></span>Python exception:
    TypeError: unsupported operand type(s) for -: &#39;tuple&#39; and &#39;list&#39;

A TypeError is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by tring to do an operation not allowed on a given type of object.

Likely cause based on the information given by Python:
    You tried to subtract two incompatible types of objects:
    a tuple and a list

Execution stopped on line 82 of file &#39;TESTS:\except\test_type_error.py&#39;.

   80:         a = (1, 2)
   81:         b = [3, 4]
--&gt;82:         result = a - b

a: (1, 2)
b: [3, 4]
</pre></div>
</div>
</div>
<div class="section" id="typeerror-3a-unsupported-operand-type-s-for">
<h2>TypeError - 3a: unsupported operand type(s) for -=<a class="headerlink" href="#typeerror-3a-unsupported-operand-type-s-for" title="Permalink to this headline">¶</a></h2>
<div class="highlight-none notranslate"><div class="highlight"><pre><span></span>Python exception:
    TypeError: unsupported operand type(s) for -=: &#39;list&#39; and &#39;tuple&#39;

A TypeError is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by tring to do an operation not allowed on a given type of object.

Likely cause based on the information given by Python:
    You tried to subtract two incompatible types of objects:
    a list and a tuple

Execution stopped on line 96 of file &#39;TESTS:\except\test_type_error.py&#39;.

   94:         a = (1, 2)
   95:         b = [3, 4]
--&gt;96:         b -= a

b: [3, 4]
a: (1, 2)
</pre></div>
</div>
</div>
<div class="section" id="typeerror-4-unsupported-operand-type-s-for">
<h2>TypeError - 4: unsupported operand type(s) for *<a class="headerlink" href="#typeerror-4-unsupported-operand-type-s-for" title="Permalink to this headline">¶</a></h2>
<div class="highlight-none notranslate"><div class="highlight"><pre><span></span>Python exception:
    TypeError: unsupported operand type(s) for *: &#39;complex&#39; and &#39;set&#39;

A TypeError is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by tring to do an operation not allowed on a given type of object.

Likely cause based on the information given by Python:
    You tried to multiply two incompatible types of objects:
    a complex number and a set

Execution stopped on line 110 of file &#39;TESTS:\except\test_type_error.py&#39;.

   108:         a = 1j
   109:         b = {2, 3}
--&gt;110:         result = a * b

a: 1j
b: {2, 3}
</pre></div>
</div>
</div>
<div class="section" id="typeerror-4a-unsupported-operand-type-s-for">
<h2>TypeError - 4a: unsupported operand type(s) for <code class="docutils literal notranslate"><span class="pre">*=</span></code><a class="headerlink" href="#typeerror-4a-unsupported-operand-type-s-for" title="Permalink to this headline">¶</a></h2>
<div class="highlight-none notranslate"><div class="highlight"><pre><span></span>Python exception:
    TypeError: unsupported operand type(s) for *=: &#39;set&#39; and &#39;complex&#39;

A TypeError is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by tring to do an operation not allowed on a given type of object.

Likely cause based on the information given by Python:
    You tried to multiply two incompatible types of objects:
    a set and a complex number

Execution stopped on line 124 of file &#39;TESTS:\except\test_type_error.py&#39;.

   122:         a = 1j
   123:         b = {2, 3}
--&gt;124:         b *= a

b: {2, 3}
a: 1j
</pre></div>
</div>
</div>
<div class="section" id="typeerror-5-unsupported-operand-type-s-for">
<h2>TypeError - 5: unsupported operand type(s) for /<a class="headerlink" href="#typeerror-5-unsupported-operand-type-s-for" title="Permalink to this headline">¶</a></h2>
<div class="highlight-none notranslate"><div class="highlight"><pre><span></span>Python exception:
    TypeError: unsupported operand type(s) for /: &#39;dict&#39; and &#39;float&#39;

A TypeError is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by tring to do an operation not allowed on a given type of object.

Likely cause based on the information given by Python:
    You tried to divide two incompatible types of objects:
    a dictionary (&#39;dict&#39;) and a number (&#39;float&#39;)

Execution stopped on line 138 of file &#39;TESTS:\except\test_type_error.py&#39;.

   136:         a = {1: 1, 2: 2}
   137:         b = 3.1416
--&gt;138:         result = a / b

a: {1: 1, 2: 2}
b: 3.1416
</pre></div>
</div>
</div>
<div class="section" id="typeerror-5a-unsupported-operand-type-s-for">
<h2>TypeError - 5a: unsupported operand type(s) for /=<a class="headerlink" href="#typeerror-5a-unsupported-operand-type-s-for" title="Permalink to this headline">¶</a></h2>
<div class="highlight-none notranslate"><div class="highlight"><pre><span></span>Python exception:
    TypeError: unsupported operand type(s) for /=: &#39;float&#39; and &#39;dict&#39;

A TypeError is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by tring to do an operation not allowed on a given type of object.

Likely cause based on the information given by Python:
    You tried to divide two incompatible types of objects:
    a number (&#39;float&#39;) and a dictionary (&#39;dict&#39;)

Execution stopped on line 152 of file &#39;TESTS:\except\test_type_error.py&#39;.

   150:         a = {1: 1, 2: 2}
   151:         b = 3.1416
--&gt;152:         b /= a

b: 3.1416
a: {1: 1, 2: 2}
</pre></div>
</div>
</div>
<div class="section" id="typeerror-5b-unsupported-operand-type-s-for">
<h2>TypeError - 5b: unsupported operand type(s) for //<a class="headerlink" href="#typeerror-5b-unsupported-operand-type-s-for" title="Permalink to this headline">¶</a></h2>
<div class="highlight-none notranslate"><div class="highlight"><pre><span></span>Python exception:
    TypeError: unsupported operand type(s) for //: &#39;dict&#39; and &#39;int&#39;

A TypeError is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by tring to do an operation not allowed on a given type of object.

Likely cause based on the information given by Python:
    You tried to divide two incompatible types of objects:
    a dictionary (&#39;dict&#39;) and an integer (&#39;int&#39;)

Execution stopped on line 166 of file &#39;TESTS:\except\test_type_error.py&#39;.

   164:         a = {1: 1, 2: 2}
   165:         b = 1
--&gt;166:         result = a // b

a: {1: 1, 2: 2}
b: 1
</pre></div>
</div>
</div>
<div class="section" id="typeerror-5c-unsupported-operand-type-s-for">
<h2>TypeError - 5c: unsupported operand type(s) for //=<a class="headerlink" href="#typeerror-5c-unsupported-operand-type-s-for" title="Permalink to this headline">¶</a></h2>
<div class="highlight-none notranslate"><div class="highlight"><pre><span></span>Python exception:
    TypeError: unsupported operand type(s) for //=: &#39;float&#39; and &#39;dict&#39;

A TypeError is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by tring to do an operation not allowed on a given type of object.

Likely cause based on the information given by Python:
    You tried to divide two incompatible types of objects:
    a number (&#39;float&#39;) and a dictionary (&#39;dict&#39;)

Execution stopped on line 180 of file &#39;TESTS:\except\test_type_error.py&#39;.

   178:         a = {1: 1, 2: 2}
   179:         b = 3.1416
--&gt;180:         b //= a

b: 3.1416
a: {1: 1, 2: 2}
</pre></div>
</div>
</div>
<div class="section" id="typeerror-6-unsupported-operand-type-s-for">
<h2>TypeError - 6: unsupported operand type(s) for &amp;<a class="headerlink" href="#typeerror-6-unsupported-operand-type-s-for" title="Permalink to this headline">¶</a></h2>
<div class="highlight-none notranslate"><div class="highlight"><pre><span></span>Python exception:
    TypeError: unsupported operand type(s) for &amp;: &#39;str&#39; and &#39;int&#39;

A TypeError is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by tring to do an operation not allowed on a given type of object.

Likely cause based on the information given by Python:
    You tried to perform the bitwise operation &amp;
    on two incompatible types of objects:
    a string (&#39;str&#39;) and an integer (&#39;int&#39;)

Execution stopped on line 194 of file &#39;TESTS:\except\test_type_error.py&#39;.

   192:         a = &quot;a&quot;
   193:         b = 2
--&gt;194:         result = a &amp; b

a: &#39;a&#39;
b: 2
</pre></div>
</div>
</div>
<div class="section" id="typeerror-6a-unsupported-operand-type-s-for">
<h2>TypeError - 6a: unsupported operand type(s) for &amp;=<a class="headerlink" href="#typeerror-6a-unsupported-operand-type-s-for" title="Permalink to this headline">¶</a></h2>
<div class="highlight-none notranslate"><div class="highlight"><pre><span></span>Python exception:
    TypeError: unsupported operand type(s) for &amp;=: &#39;int&#39; and &#39;str&#39;

A TypeError is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by tring to do an operation not allowed on a given type of object.

Likely cause based on the information given by Python:
    You tried to perform the bitwise operation &amp;=
    on two incompatible types of objects:
    an integer (&#39;int&#39;) and a string (&#39;str&#39;)

Execution stopped on line 208 of file &#39;TESTS:\except\test_type_error.py&#39;.

   206:         a = &quot;a&quot;
   207:         b = 2
--&gt;208:         b &amp;= a

b: 2
a: &#39;a&#39;
</pre></div>
</div>
</div>
<div class="section" id="typeerror-7-unsupported-operand-type-s-for">
<h2>TypeError - 7: unsupported operand type(s) for **<a class="headerlink" href="#typeerror-7-unsupported-operand-type-s-for" title="Permalink to this headline">¶</a></h2>
<div class="highlight-none notranslate"><div class="highlight"><pre><span></span>Python exception:
    TypeError: unsupported operand type(s) for ** or pow(): &#39;dict&#39; and &#39;float&#39;

A TypeError is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by tring to do an operation not allowed on a given type of object.

Likely cause based on the information given by Python:
    You tried to exponentiate (raise to a power)
    using two incompatible types of objects:
    a dictionary (&#39;dict&#39;) and a number (&#39;float&#39;)

Execution stopped on line 222 of file &#39;TESTS:\except\test_type_error.py&#39;.

   220:         a = {1: 1, 2: 2}
   221:         b = 3.1416
--&gt;222:         result = a ** b

a: {1: 1, 2: 2}
b: 3.1416
</pre></div>
</div>
</div>
<div class="section" id="typeerror-7a-unsupported-operand-type-s-for">
<h2>TypeError - 7a: unsupported operand type(s) for <code class="docutils literal notranslate"><span class="pre">**=</span></code><a class="headerlink" href="#typeerror-7a-unsupported-operand-type-s-for" title="Permalink to this headline">¶</a></h2>
<div class="highlight-none notranslate"><div class="highlight"><pre><span></span>Python exception:
    TypeError: unsupported operand type(s) for ** or pow(): &#39;dict&#39; and &#39;float&#39;

A TypeError is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by tring to do an operation not allowed on a given type of object.

Likely cause based on the information given by Python:
    You tried to exponentiate (raise to a power)
    using two incompatible types of objects:
    a dictionary (&#39;dict&#39;) and a number (&#39;float&#39;)

Execution stopped on line 236 of file &#39;TESTS:\except\test_type_error.py&#39;.

   234:         a = {1: 1, 2: 2}
   235:         b = 3.1416
--&gt;236:         a **= b

a: {1: 1, 2: 2}
b: 3.1416
</pre></div>
</div>
</div>
<div class="section" id="typeerror-8-unsupported-operand-type-s-for">
<h2>TypeError - 8: unsupported operand type(s) for &gt;&gt;<a class="headerlink" href="#typeerror-8-unsupported-operand-type-s-for" title="Permalink to this headline">¶</a></h2>
<div class="highlight-none notranslate"><div class="highlight"><pre><span></span>Python exception:
    TypeError: unsupported operand type(s) for &gt;&gt;: &#39;str&#39; and &#39;int&#39;

A TypeError is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by tring to do an operation not allowed on a given type of object.

Likely cause based on the information given by Python:
    You tried to perform the bit shifting operation &gt;&gt;
    on two incompatible types of objects:
    a string (&#39;str&#39;) and an integer (&#39;int&#39;)

Execution stopped on line 250 of file &#39;TESTS:\except\test_type_error.py&#39;.

   248:         a = &quot;a&quot;
   249:         b = 42
--&gt;250:         result = a &gt;&gt; b

a: &#39;a&#39;
b: 42
</pre></div>
</div>
</div>
<div class="section" id="typeerror-8a-unsupported-operand-type-s-for">
<h2>TypeError - 8a: unsupported operand type(s) for &gt;&gt;=<a class="headerlink" href="#typeerror-8a-unsupported-operand-type-s-for" title="Permalink to this headline">¶</a></h2>
<div class="highlight-none notranslate"><div class="highlight"><pre><span></span>Python exception:
    TypeError: unsupported operand type(s) for &gt;&gt;=: &#39;str&#39; and &#39;int&#39;

A TypeError is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by tring to do an operation not allowed on a given type of object.

Likely cause based on the information given by Python:
    You tried to perform the bit shifting operation &gt;&gt;=
    on two incompatible types of objects:
    a string (&#39;str&#39;) and an integer (&#39;int&#39;)

Execution stopped on line 264 of file &#39;TESTS:\except\test_type_error.py&#39;.

   262:         a = &quot;a&quot;
   263:         b = 42
--&gt;264:         a &gt;&gt;= b

a: &#39;a&#39;
b: 42
</pre></div>
</div>
</div>
<div class="section" id="typeerror-9-unsupported-operand-type-s-for">
<h2>TypeError - 9: unsupported operand type(s) for &#64;<a class="headerlink" href="#typeerror-9-unsupported-operand-type-s-for" title="Permalink to this headline">¶</a></h2>
<div class="highlight-none notranslate"><div class="highlight"><pre><span></span>Python exception:
    TypeError: unsupported operand type(s) for @: &#39;str&#39; and &#39;int&#39;

A TypeError is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by tring to do an operation not allowed on a given type of object.

Likely cause based on the information given by Python:
    You tried to use the operator @
    using two incompatible types of objects:
    a string (&#39;str&#39;) and an integer (&#39;int&#39;).
    This operator is normally used only
    for multiplication of matrices.

Execution stopped on line 278 of file &#39;TESTS:\except\test_type_error.py&#39;.

   276:         a = &quot;a&quot;
   277:         b = 2
--&gt;278:         result = a @ b

a: &#39;a&#39;
b: 2
</pre></div>
</div>
</div>
<div class="section" id="typeerror-9a-unsupported-operand-type-s-for">
<h2>TypeError - 9a: unsupported operand type(s) for &#64;=<a class="headerlink" href="#typeerror-9a-unsupported-operand-type-s-for" title="Permalink to this headline">¶</a></h2>
<div class="highlight-none notranslate"><div class="highlight"><pre><span></span>Python exception:
    TypeError: unsupported operand type(s) for @=: &#39;str&#39; and &#39;int&#39;

A TypeError is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by tring to do an operation not allowed on a given type of object.

Likely cause based on the information given by Python:
    You tried to use the operator @=
    using two incompatible types of objects:
    a string (&#39;str&#39;) and an integer (&#39;int&#39;).
    This operator is normally used only
    for multiplication of matrices.

Execution stopped on line 292 of file &#39;TESTS:\except\test_type_error.py&#39;.

   290:         a = &quot;a&quot;
   291:         b = 2
--&gt;292:         a @= b

a: &#39;a&#39;
b: 2
</pre></div>
</div>
</div>
<div class="section" id="typeerror-10-comparison-between-incompatible-types">
<h2>TypeError - 10: comparison between incompatible types<a class="headerlink" href="#typeerror-10-comparison-between-incompatible-types" title="Permalink to this headline">¶</a></h2>
<div class="highlight-none notranslate"><div class="highlight"><pre><span></span>Python exception:
    TypeError: &#39;&lt;&#39; not supported between instances of &#39;int&#39; and &#39;str&#39;

A TypeError is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by tring to do an operation not allowed on a given type of object.

Likely cause based on the information given by Python:
    You tried to do an order comparison (&lt;)
    between two incompatible types of objects:
    an integer (&#39;int&#39;) and a string (&#39;str&#39;)

Execution stopped on line 306 of file &#39;TESTS:\except\test_type_error.py&#39;.

   304:         a = &quot;a&quot;
   305:         b = 42
--&gt;306:         b &lt; a

b: 42
a: &#39;a&#39;
</pre></div>
</div>
</div>
<div class="section" id="typeerror-11-bad-operand-type-for-unary">
<h2>TypeError - 11: bad operand type for unary +<a class="headerlink" href="#typeerror-11-bad-operand-type-for-unary" title="Permalink to this headline">¶</a></h2>
<div class="highlight-none notranslate"><div class="highlight"><pre><span></span>Python exception:
    TypeError: bad operand type for unary +: &#39;str&#39;

A TypeError is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by tring to do an operation not allowed on a given type of object.

Likely cause based on the information given by Python:
    You tried to use the unary operator &#39;+&#39;
    with the following type of object: a string (&#39;str&#39;).
    This operation is not defined for this type of object.

Execution stopped on line 318 of file &#39;TESTS:\except\test_type_error.py&#39;.

   316: def test_type_error11():
   317:     try:
--&gt;318:         a = +&quot;abc&quot;
</pre></div>
</div>
</div>
<div class="section" id="typeerror-11a-bad-operand-type-for-unary">
<h2>TypeError - 11a: bad operand type for unary -<a class="headerlink" href="#typeerror-11a-bad-operand-type-for-unary" title="Permalink to this headline">¶</a></h2>
<div class="highlight-none notranslate"><div class="highlight"><pre><span></span>Python exception:
    TypeError: bad operand type for unary -: &#39;list&#39;

A TypeError is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by tring to do an operation not allowed on a given type of object.

Likely cause based on the information given by Python:
    You tried to use the unary operator &#39;-&#39;
    with the following type of object: a list.
    This operation is not defined for this type of object.

Execution stopped on line 331 of file &#39;TESTS:\except\test_type_error.py&#39;.

   329: def test_type_error11a():
   330:     try:
--&gt;331:         a = -[1, 2, 3]
</pre></div>
</div>
</div>
<div class="section" id="typeerror-11b-bad-operand-type-for-unary">
<h2>TypeError - 11b: bad operand type for unary ~<a class="headerlink" href="#typeerror-11b-bad-operand-type-for-unary" title="Permalink to this headline">¶</a></h2>
<div class="highlight-none notranslate"><div class="highlight"><pre><span></span>Python exception:
    TypeError: bad operand type for unary ~: &#39;tuple&#39;

A TypeError is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by tring to do an operation not allowed on a given type of object.

Likely cause based on the information given by Python:
    You tried to use the unary operator &#39;~&#39;
    with the following type of object: a tuple.
    This operation is not defined for this type of object.

Execution stopped on line 344 of file &#39;TESTS:\except\test_type_error.py&#39;.

   342: def test_type_error11b():
   343:     try:
--&gt;344:         a = ~(1, 2, 3)
</pre></div>
</div>
</div>
<div class="section" id="typeerror-12-object-does-not-support-item-assignment">
<h2>TypeError - 12: object does not support item assignment<a class="headerlink" href="#typeerror-12-object-does-not-support-item-assignment" title="Permalink to this headline">¶</a></h2>
<div class="highlight-none notranslate"><div class="highlight"><pre><span></span>Python exception:
    TypeError: &#39;tuple&#39; object does not support item assignment

A TypeError is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by tring to do an operation not allowed on a given type of object.

Likely cause based on the information given by Python:
    In Python, some objects are known as immutable:
    once defined, their value cannot be changed.
    You tried change part of such an immutable object: a tuple,
    most likely by using an indexing operation.

Execution stopped on line 358 of file &#39;TESTS:\except\test_type_error.py&#39;.

   356:     a = (1, 2, 3)
   357:     try:
--&gt;358:         a[0] = 0

a: (1, 2, 3)
</pre></div>
</div>
</div>
<div class="section" id="typeerror-13-wrong-number-of-positional-arguments">
<h2>TypeError - 13: wrong number of positional arguments<a class="headerlink" href="#typeerror-13-wrong-number-of-positional-arguments" title="Permalink to this headline">¶</a></h2>
<div class="highlight-none notranslate"><div class="highlight"><pre><span></span>Python exception:
    TypeError: fn() takes 0 positional arguments but 1 was given

A TypeError is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by tring to do an operation not allowed on a given type of object.

Likely cause based on the information given by Python:
    You apparently have called the function &#39;fn()&#39; with
    1 positional argument while it requires 0
    such positional arguments.

Execution stopped on line 373 of file &#39;TESTS:\except\test_type_error.py&#39;.

   371:
   372:     try:
--&gt;373:         fn(1)

fn: &lt;function test_type_error13.&lt;locals&gt;.fn&gt;
</pre></div>
</div>
</div>
<div class="section" id="typeerror-14-missing-positional-arguments">
<h2>TypeError - 14: missing positional arguments<a class="headerlink" href="#typeerror-14-missing-positional-arguments" title="Permalink to this headline">¶</a></h2>
<div class="highlight-none notranslate"><div class="highlight"><pre><span></span>Python exception:
    TypeError: fn() missing 2 required positional arguments: &#39;b&#39; and &#39;c&#39;

A TypeError is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by tring to do an operation not allowed on a given type of object.

Likely cause based on the information given by Python:
    You apparently have called the function &#39;fn()&#39; with
    fewer positional arguments than it requires (2 missing).

Execution stopped on line 388 of file &#39;TESTS:\except\test_type_error.py&#39;.

   386:
   387:     try:
--&gt;388:         fn(1)

fn: &lt;function test_type_error14.&lt;locals&gt;.fn&gt;
</pre></div>
</div>
</div>
<div class="section" id="typeerror-15-tuple-object-is-not-callable">
<h2>TypeError - 15: tuple object is not callable<a class="headerlink" href="#typeerror-15-tuple-object-is-not-callable" title="Permalink to this headline">¶</a></h2>
<div class="highlight-none notranslate"><div class="highlight"><pre><span></span>Python exception:
    TypeError: &#39;tuple&#39; object is not callable

A TypeError is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by tring to do an operation not allowed on a given type of object.

Likely cause based on the information given by Python:
    I suspect that you had an object of this type, &lt;a tuple&gt;,
    followed by what looked like a tuple, &#39;(...)&#39;,
    which Python took as an indication of a function call.
    Perhaps you had a missing comma before the tuple.

Execution stopped on line 400 of file &#39;TESTS:\except\test_type_error.py&#39;.

   398: def test_type_error15():
   399:     try:
--&gt;400:         _ = (1, 2)(3, 4)
</pre></div>
</div>
</div>
<div class="section" id="typeerror-15a-list-object-is-not-callable">
<h2>TypeError - 15a: list object is not callable<a class="headerlink" href="#typeerror-15a-list-object-is-not-callable" title="Permalink to this headline">¶</a></h2>
<div class="highlight-none notranslate"><div class="highlight"><pre><span></span>Python exception:
    TypeError: &#39;list&#39; object is not callable

A TypeError is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by tring to do an operation not allowed on a given type of object.

Likely cause based on the information given by Python:
    I suspect that you had an object of this type, &lt;a list&gt;,
    followed by what looked like a tuple, &#39;(...)&#39;,
    which Python took as an indication of a function call.
    Perhaps you had a missing comma before the tuple.

Execution stopped on line 412 of file &#39;TESTS:\except\test_type_error.py&#39;.

   410: def test_type_error15a():
   411:     try:
--&gt;412:         _ = [1, 2](3, 4)
</pre></div>
</div>
</div>
<div class="section" id="unboundlocalerror">
<h2>UnboundLocalError<a class="headerlink" href="#unboundlocalerror" title="Permalink to this headline">¶</a></h2>
<div class="highlight-none notranslate"><div class="highlight"><pre><span></span>Python exception:
    UnboundLocalError: local variable &#39;a&#39; referenced before assignment

In Python, variables that are used inside a function are known as
local variables. Before they are used, they must be assigned a value.
A variable that is used before it is assigned a value is assumed to
be defined outside that function; it is known as a &#39;global&#39;
(or sometimes &#39;nonlocal&#39;) variable. You cannot assign a value to such
a global variable inside a function without first indicating to
Python that this is a global variable, otherwise you will see
an UnboundLocalError.

Likely cause based on the information given by Python:
    The variable that appears to cause the problem is &#39;a&#39;.
    Perhaps the statement
        global a
    should have been included as the first line inside your function.

Execution stopped on line 21 of file &#39;TESTS:\except\test_unbound_local_error.py&#39;.

   19:
   20:     try:
--&gt;21:         outer()

global outer: &lt;function outer&gt;

Exception raised on line 12 of file &#39;TESTS:\except\test_unbound_local_error.py&#39;.

   10:     def inner():
   11:         c = 3
--&gt;12:         a = a + b + c

global b: 2
c: 3
</pre></div>
</div>
</div>
<div class="section" id="unknown-exception">
<h2>Unknown exception<a class="headerlink" href="#unknown-exception" title="Permalink to this headline">¶</a></h2>
<div class="highlight-none notranslate"><div class="highlight"><pre><span></span>Python exception:
    MyException: Some informative message about an unknown exception.

No information is known about this exception.
Please report this example to
https://github.com/aroberge/friendly-traceback/issues

Execution stopped on line 10 of file &#39;TESTS:\except\test_unknown_error.py&#39;.

    8: def test_unknown_error():
    9:     try:
--&gt;10:         raise MyException(&quot;Some informative message about an unknown exception.&quot;)

global MyException: &lt;class &#39;test_unknown_error.MyException&#39;&gt;
</pre></div>
</div>
</div>
<div class="section" id="zerodivisionerror-1">
<h2>ZeroDivisionError - 1<a class="headerlink" href="#zerodivisionerror-1" title="Permalink to this headline">¶</a></h2>
<div class="highlight-none notranslate"><div class="highlight"><pre><span></span>Python exception:
    ZeroDivisionError: division by zero

A ZeroDivisionError occurs when you are attempting to divide
a value by zero:
    result = my_variable / 0
It can also happen if you calculate the remainder of a division
using the modulo operator &#39;%&#39;
    result = my_variable % 0

Execution stopped on line 6 of file &#39;TESTS:\except\test_zero_division_error.py&#39;.

   4: def test_zero_division_error():
   5:     try:
--&gt;6:         1 / 0
</pre></div>
</div>
</div>
<div class="section" id="zerodivisionerror-2">
<h2>ZeroDivisionError - 2<a class="headerlink" href="#zerodivisionerror-2" title="Permalink to this headline">¶</a></h2>
<div class="highlight-none notranslate"><div class="highlight"><pre><span></span>Python exception:
    ZeroDivisionError: integer division or modulo by zero

A ZeroDivisionError occurs when you are attempting to divide
a value by zero:
    result = my_variable / 0
It can also happen if you calculate the remainder of a division
using the modulo operator &#39;%&#39;
    result = my_variable % 0

Execution stopped on line 19 of file &#39;TESTS:\except\test_zero_division_error.py&#39;.

   17:     zero = 0
   18:     try:
--&gt;19:         1 % zero

zero: 0
</pre></div>
</div>
</div>
</div>


           </div>
           
          </div>
          <footer>
  
    <div class="rst-footer-buttons" role="navigation" aria-label="footer navigation">
      
        <a href="syntax_tracebacks_en_3.6.html" class="btn btn-neutral float-right" title="Friendly SyntaxError tracebacks - in English" accesskey="n" rel="next">Next <span class="fa fa-arrow-circle-right"></span></a>
      
      
        <a href="compare.html" class="btn btn-neutral float-left" title="Comparison between Python versions" accesskey="p" rel="prev"><span class="fa fa-arrow-circle-left"></span> Previous</a>
      
    </div>
  

  <hr/>

  <div role="contentinfo">
    <p>
        &copy; Copyright 2019, André Roberge

    </p>
  </div>
  Built with <a href="http://sphinx-doc.org/">Sphinx</a> using a <a href="https://github.com/rtfd/sphinx_rtd_theme">theme</a> provided by <a href="https://readthedocs.org">Read the Docs</a>. 

</footer>

        </div>
      </div>

    </section>

  </div>
  


  <script type="text/javascript">
      jQuery(function () {
          SphinxRtdTheme.Navigation.enable(true);
      });
  </script>

  
  
    
   

</body>
</html>