

<!DOCTYPE html>
<html class="writer-html5" lang="en" >
<head>
  <meta charset="utf-8">
  
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  
  <title>Verbosity: how much information do we want? &mdash; Friendly tracebacks 0.0.39a documentation</title>
  

  
  <link rel="stylesheet" href="_static/css/theme.css" type="text/css" />
  <link rel="stylesheet" href="_static/pygments.css" type="text/css" />
  <link rel="stylesheet" href="_static/custom.css" type="text/css" />

  
  
  
  

  
  <!--[if lt IE 9]>
    <script src="_static/js/html5shiv.min.js"></script>
  <![endif]-->
  
    
      <script type="text/javascript" id="documentation_options" data-url_root="./" src="_static/documentation_options.js"></script>
        <script src="_static/jquery.js"></script>
        <script src="_static/underscore.js"></script>
        <script src="_static/doctools.js"></script>
        <script src="_static/language_data.js"></script>
    
    <script type="text/javascript" src="_static/js/theme.js"></script>

    
    <link rel="index" title="Index" href="genindex.html" />
    <link rel="search" title="Search" href="search.html" /> 
</head>

<body class="wy-body-for-nav">

   
  <div class="wy-grid-for-nav">
    
    <nav data-toggle="wy-nav-shift" class="wy-nav-side">
      <div class="wy-side-scroll">
        <div class="wy-side-nav-search" >
          

          
            <a href="index.html" class="icon icon-home" alt="Documentation Home"> Friendly tracebacks
          

          
          </a>

          
            
            
              <div class="version">
                0.0.39a
              </div>
            
          

          
<div role="search">
  <form id="rtd-search-form" class="wy-form" action="search.html" method="get">
    <input type="text" name="q" placeholder="Search docs" />
    <input type="hidden" name="check_keywords" value="yes" />
    <input type="hidden" name="area" value="default" />
  </form>
</div>

          
        </div>

        
        <div class="wy-menu wy-menu-vertical" data-spy="affix" role="navigation" aria-label="main navigation">
          
            
            
              
            
            
              <p class="caption"><span class="caption-text">For beginners and teachers</span></p>
<ul>
<li class="toctree-l1"><a class="reference internal" href="usage.html">Usage</a></li>
<li class="toctree-l1"><a class="reference internal" href="thonny.html">Using with Thonny</a></li>
<li class="toctree-l1"><a class="reference internal" href="mu.html">Using with Mu</a></li>
</ul>
<p class="caption"><span class="caption-text">Thoughts on design</span></p>
<ul>
<li class="toctree-l1"><a class="reference internal" href="design.html">Some thoughts on the design of friendly-traceback</a></li>
</ul>
<p class="caption"><span class="caption-text">More advanced users</span></p>
<ul>
<li class="toctree-l1"><a class="reference internal" href="usage_adv.html">Advanced Usage</a></li>
</ul>
<p class="caption"><span class="caption-text">Use in your project</span></p>
<ul>
<li class="toctree-l1"><a class="reference internal" href="custom.html">Description of demos</a></li>
<li class="toctree-l1"><a class="reference internal" href="api.html">Public API</a></li>
<li class="toctree-l1"><a class="reference internal" href="graph.html">Project files</a></li>
<li class="toctree-l1"><a class="reference internal" href="lies.html">Intentional lies</a></li>
</ul>
<p class="caption"><span class="caption-text">Contribute</span></p>
<ul>
<li class="toctree-l1"><a class="reference internal" href="suggest.html">Suggest an addition</a></li>
<li class="toctree-l1"><a class="reference internal" href="adding_exception.html">Developer: Add a new Exception case</a></li>
<li class="toctree-l1"><a class="reference internal" href="syntax_error.html">Developer: Add a new SyntaxError case</a></li>
<li class="toctree-l1"><a class="reference internal" href="translation_notes.html">Notes on translations - using gettext</a></li>
</ul>
<p class="caption"><span class="caption-text">All the tracebacks!</span></p>
<ul>
<li class="toctree-l1"><a class="reference internal" href="known.html">Known exceptions</a></li>
<li class="toctree-l1"><a class="reference internal" href="tracebacks_en_3.6.html">Friendly tracebacks - Python 3.6 in English</a></li>
<li class="toctree-l1"><a class="reference internal" href="syntax_tracebacks_en_3.6.html">SyntaxError - Python 3.6 in English</a></li>
<li class="toctree-l1"><a class="reference internal" href="tracebacks_en_3.7.html">Friendly tracebacks - Python 3.7 in English</a></li>
<li class="toctree-l1"><a class="reference internal" href="syntax_tracebacks_en_3.7.html">SyntaxError - Python 3.7 in English</a></li>
<li class="toctree-l1"><a class="reference internal" href="tracebacks_en_3.8.html">Friendly tracebacks - Python 3.8 in English</a></li>
<li class="toctree-l1"><a class="reference internal" href="syntax_tracebacks_en_3.8.html">SyntaxError - Python 3.8 in English</a></li>
<li class="toctree-l1"><a class="reference internal" href="tracebacks_en_3.9.html">Friendly tracebacks - Python 3.9 in English</a></li>
<li class="toctree-l1"><a class="reference internal" href="syntax_tracebacks_en_3.9.html">SyntaxError - Python 3.9 in English</a></li>
<li class="toctree-l1"><a class="reference internal" href="compare.html">Comparison between Python versions</a></li>
</ul>
<p class="caption"><span class="caption-text">Markdown examples</span></p>
<ul>
<li class="toctree-l1"><a class="reference internal" href="tracebacks_markdown.html">Friendly tracebacks - markdown_docs format</a></li>
<li class="toctree-l1"><a class="reference internal" href="tracebacks_syntax_markdown.html">Syntax errors - markdown_docs format</a></li>
</ul>
<p class="caption"><span class="caption-text">En français</span></p>
<ul>
<li class="toctree-l1"><a class="reference internal" href="tracebacks_fr.html"> Friendly tracebacks - en Français</a></li>
<li class="toctree-l1"><a class="reference internal" href="syntax_tracebacks_fr.html"> Friendly SyntaxError tracebacks - en Français</a></li>
</ul>
<p class="caption"><span class="caption-text">varia</span></p>
<ul>
<li class="toctree-l1"><a class="reference internal" href="changelog.html">Change Log</a></li>
</ul>

            
          
        </div>
        
      </div>
    </nav>

    <section data-toggle="wy-nav-shift" class="wy-nav-content-wrap">

      
      <nav class="wy-nav-top" aria-label="top navigation">
        
          <i data-toggle="wy-nav-top" class="fa fa-bars"></i>
          <a href="index.html">Friendly tracebacks</a>
        
      </nav>


      <div class="wy-nav-content">
        
        <div class="rst-content style-external-links">
        
          















<div role="navigation" aria-label="breadcrumbs navigation">

  <ul class="wy-breadcrumbs">
    
      <li><a href="index.html" class="icon icon-home"></a> &raquo;</li>
        
      <li>Verbosity: how much information do we want?</li>
    
    
      <li class="wy-breadcrumbs-aside">
        
            
            <a href="_sources/verbosity_3.8.rst.txt" rel="nofollow"> View page source</a>
          
        
      </li>
    
  </ul>

  
  <hr/>
</div>
          <div role="main" class="document" itemscope="itemscope" itemtype="http://schema.org/Article">
           <div itemprop="articleBody">
            
  <div class="admonition warning">
<p class="admonition-title">Warning</p>
<p>This is alpha software, currently in development.
The API is subject to change without notice;
many such changes are not yet included in this documentation.
The aim is to have (almost) all the text updated and corrected
by the time version 0.1 is released, at which time this warning
will change.</p>
<p>Note that most screenshots have been taken with an obsolete version.
We aim to replace those when work for version 0.2 has been completed.</p>
</div>
<p>Friendly-traceback version: 0.0.39a
Python version: 3.8.4</p>
<div class="section" id="verbosity-how-much-information-do-we-want">
<h1>Verbosity: how much information do we want?<a class="headerlink" href="#verbosity-how-much-information-do-we-want" title="Permalink to this headline">¶</a></h1>
<p>Suppose we try to run following program</p>
<div class="highlight-python notranslate"><table class="highlighttable"><tr><td class="linenos"><div class="linenodiv"><pre> 1
 2
 3
 4
 5
 6
 7
 8
 9
10
11
12
13
14
15
16</pre></div></td><td class="code"><div class="highlight"><pre><span></span> <span class="c1"># Used with test_verbosity.py</span>

 <span class="n">a_1</span> <span class="o">=</span> <span class="mi">2</span>

 <span class="k">def</span> <span class="nf">function_1</span><span class="p">(</span><span class="n">a</span><span class="p">):</span>
     <span class="n">a_2</span> <span class="o">=</span> <span class="mi">4</span>
     <span class="n">a_1</span> <span class="o">=</span> <span class="n">a_1</span> <span class="o">+</span> <span class="n">a_2</span> <span class="o">+</span> <span class="n">a</span>

 <span class="k">def</span> <span class="nf">function_2</span><span class="p">(</span><span class="n">y</span><span class="p">):</span>
     <span class="k">return</span> <span class="n">function_1</span><span class="p">(</span><span class="n">y</span> <span class="o">+</span> <span class="mi">1</span><span class="p">)</span>


 <span class="k">def</span> <span class="nf">function_3</span><span class="p">(</span><span class="n">x</span><span class="p">):</span>
     <span class="k">return</span> <span class="mi">3</span> <span class="o">*</span> <span class="n">function_2</span><span class="p">(</span><span class="n">x</span><span class="p">)</span>

 <span class="n">function_3</span><span class="p">(</span><span class="mi">1</span><span class="p">)</span>
</pre></div>
</td></tr></table></div>
<p>It would generate the following traceback:</p>
<div class="highlight-none notranslate"><div class="highlight"><pre><span></span>Traceback (most recent call last):
  File &quot;unbound_local_error.py&quot;, line 16, in &lt;module&gt;
    function_3(1)
  File &quot;unbound_local_error.py&quot;, line 14, in function_3
    return 3 * function_2(x)
  File &quot;unbound_local_error.py&quot;, line 10, in function_2
    return function_1(y + 1)
  File &quot;unbound_local_error.py&quot;, line 7, in function_1
    a_1 = a_1 + a_2 + a
UnboundLocalError: local variable &#39;a_1&#39; referenced before assignment
</pre></div>
</div>
<p>Confronted with such a terse output, a beginner might be confused
as to what it means.</p>
<ul class="simple">
<li><p>What does “most recent call last” mean?</p></li>
<li><p>What is an UnboundLocalError?</p></li>
<li><p>What does it mean to be referenced before assignment?</p></li>
<li><p>What do I need to do to fix this error?</p></li>
<li><p>etc.</p></li>
</ul>
<p>This might be even more acute if this beginner does not understand
English.</p>
<p>Friendly-traceback attempts to provide all the information to
understand what might have gone wrong and, hopefully, how to fix it.
Other than the name of the exception (UnboundLocalError) and
the message generated by Python
(local variable ‘a_1’ referenced before assignment),
all the text provided by Friendly-traceback is translatable;
currently, only the original English version and a French translation
are available.</p>
<p>Instead of showing all the different calls,
Friendly-traceback only shows two locations:
where the program stopped, and where the exception
was actually raised.</p>
<p>In some cases, the amount of information given by Friendly-traceback
using the default values might not be appropriate. This can
be adjusted by selecting a different “verbosity” level, as elsewhere.</p>
<p>Below, we show what content is included for each level.</p>
<div class="section" id="verbosity-level-1-the-default">
<h2>Verbosity level 1: the default<a class="headerlink" href="#verbosity-level-1-the-default" title="Permalink to this headline">¶</a></h2>
<p>This includes all the custom information provided by Friendly-traceback.
It does not include a standard Python traceback.</p>
<div class="highlight-none notranslate"><div class="highlight"><pre><span></span>Python exception:
    UnboundLocalError: local variable &#39;a_1&#39; referenced before assignment

In Python, variables that are used inside a function are known as
local variables. Before they are used, they must be assigned a value.
A variable that is used before it is assigned a value is assumed to
be defined outside that function; it is known as a `global`
(or sometimes `nonlocal`) variable. You cannot assign a value to such
a global variable inside a function without first indicating to
Python that this is a global variable, otherwise you will see
an `UnboundLocalError`.

Likely cause based on the information given by Python:
    The variable that appears to cause the problem is `a_1`.
    Perhaps the statement

        global a_1

    should have been included as the first line inside your function.
    The similar name `&#39;a_2&#39;` was found in the local scope.

Execution stopped on line 16 of file &#39;unbound_local_error.py&#39;.

   13: def function_3(x):
   14:     return 3 * function_2(x)
   15:
--&gt;16: function_3(1)

    Known identifiers:
        function_3: &lt;function function_3&gt;

Exception raised on line 7 of file &#39;unbound_local_error.py&#39;.

    4:
    5: def function_1(a):
    6:     a_2 = 4
--&gt; 7:     a_1 = a_1 + a_2 + a

    Known identifiers:
        global a_1: 2
        a_2: 4
        a: 2
</pre></div>
</div>
</div>
<div class="section" id="verbosity-level-2">
<h2>Verbosity level 2<a class="headerlink" href="#verbosity-level-2" title="Permalink to this headline">¶</a></h2>
<p>This is the same as level 1 with the addition of a Python traceback
preceding the information given in level 1.</p>
<div class="highlight-none notranslate"><div class="highlight"><pre><span></span>Traceback (most recent call last):
  File &quot;unbound_local_error.py&quot;, line 16, in &lt;module&gt;
    function_3(1)
  File &quot;unbound_local_error.py&quot;, line 14, in function_3
    return 3 * function_2(x)
  File &quot;unbound_local_error.py&quot;, line 10, in function_2
    return function_1(y + 1)
  File &quot;unbound_local_error.py&quot;, line 7, in function_1
    a_1 = a_1 + a_2 + a
UnboundLocalError: local variable &#39;a_1&#39; referenced before assignment

Python exception:
    UnboundLocalError: local variable &#39;a_1&#39; referenced before assignment

In Python, variables that are used inside a function are known as
local variables. Before they are used, they must be assigned a value.
A variable that is used before it is assigned a value is assumed to
be defined outside that function; it is known as a `global`
(or sometimes `nonlocal`) variable. You cannot assign a value to such
a global variable inside a function without first indicating to
Python that this is a global variable, otherwise you will see
an `UnboundLocalError`.

Likely cause based on the information given by Python:
    The variable that appears to cause the problem is `a_1`.
    Perhaps the statement

        global a_1

    should have been included as the first line inside your function.
    The similar name `&#39;a_2&#39;` was found in the local scope.

Execution stopped on line 16 of file &#39;unbound_local_error.py&#39;.

   13: def function_3(x):
   14:     return 3 * function_2(x)
   15:
--&gt;16: function_3(1)

    Known identifiers:
        function_3: &lt;function function_3&gt;

Exception raised on line 7 of file &#39;unbound_local_error.py&#39;.

    4:
    5: def function_1(a):
    6:     a_2 = 4
--&gt; 7:     a_1 = a_1 + a_2 + a

    Known identifiers:
        global a_1: 2
        a_2: 4
        a: 2
</pre></div>
</div>
</div>
<div class="section" id="verbosity-level-3">
<h2>Verbosity level 3<a class="headerlink" href="#verbosity-level-3" title="Permalink to this headline">¶</a></h2>
<p>This is the same as level 1 with the addition of a Python traceback
after the information given in level 1.</p>
<div class="highlight-none notranslate"><div class="highlight"><pre><span></span>Python exception:
    UnboundLocalError: local variable &#39;a_1&#39; referenced before assignment

In Python, variables that are used inside a function are known as
local variables. Before they are used, they must be assigned a value.
A variable that is used before it is assigned a value is assumed to
be defined outside that function; it is known as a `global`
(or sometimes `nonlocal`) variable. You cannot assign a value to such
a global variable inside a function without first indicating to
Python that this is a global variable, otherwise you will see
an `UnboundLocalError`.

Likely cause based on the information given by Python:
    The variable that appears to cause the problem is `a_1`.
    Perhaps the statement

        global a_1

    should have been included as the first line inside your function.
    The similar name `&#39;a_2&#39;` was found in the local scope.

Execution stopped on line 16 of file &#39;unbound_local_error.py&#39;.

   13: def function_3(x):
   14:     return 3 * function_2(x)
   15:
--&gt;16: function_3(1)

    Known identifiers:
        function_3: &lt;function function_3&gt;

Exception raised on line 7 of file &#39;unbound_local_error.py&#39;.

    4:
    5: def function_1(a):
    6:     a_2 = 4
--&gt; 7:     a_1 = a_1 + a_2 + a

    Known identifiers:
        global a_1: 2
        a_2: 4
        a: 2

Traceback (most recent call last):
  File &quot;unbound_local_error.py&quot;, line 16, in &lt;module&gt;
    function_3(1)
  File &quot;unbound_local_error.py&quot;, line 14, in function_3
    return 3 * function_2(x)
  File &quot;unbound_local_error.py&quot;, line 10, in function_2
    return function_1(y + 1)
  File &quot;unbound_local_error.py&quot;, line 7, in function_1
    a_1 = a_1 + a_2 + a
UnboundLocalError: local variable &#39;a_1&#39; referenced before assignment
</pre></div>
</div>
</div>
<div class="section" id="verbosity-level-4">
<h2>Verbosity level 4<a class="headerlink" href="#verbosity-level-4" title="Permalink to this headline">¶</a></h2>
<p>This is similar to level 1 except that the generic meaning of
a given exception (“what do we mean by UnboundLocalError…”)
is <strong>not</strong> included.</p>
<div class="highlight-none notranslate"><div class="highlight"><pre><span></span>Python exception:
    UnboundLocalError: local variable &#39;a_1&#39; referenced before assignment

Likely cause based on the information given by Python:
    The variable that appears to cause the problem is `a_1`.
    Perhaps the statement

        global a_1

    should have been included as the first line inside your function.
    The similar name `&#39;a_2&#39;` was found in the local scope.

Execution stopped on line 16 of file &#39;unbound_local_error.py&#39;.

   13: def function_3(x):
   14:     return 3 * function_2(x)
   15:
--&gt;16: function_3(1)

    Known identifiers:
        function_3: &lt;function function_3&gt;

Exception raised on line 7 of file &#39;unbound_local_error.py&#39;.

    4:
    5: def function_1(a):
    6:     a_2 = 4
--&gt; 7:     a_1 = a_1 + a_2 + a

    Known identifiers:
        global a_1: 2
        a_2: 4
        a: 2
</pre></div>
</div>
</div>
<div class="section" id="verbosity-level-5">
<h2>Verbosity level 5<a class="headerlink" href="#verbosity-level-5" title="Permalink to this headline">¶</a></h2>
<p>Same as level 4, with the addition of a Python traceback before
the rest of the information.</p>
<div class="highlight-none notranslate"><div class="highlight"><pre><span></span>Traceback (most recent call last):
  File &quot;unbound_local_error.py&quot;, line 16, in &lt;module&gt;
    function_3(1)
  File &quot;unbound_local_error.py&quot;, line 14, in function_3
    return 3 * function_2(x)
  File &quot;unbound_local_error.py&quot;, line 10, in function_2
    return function_1(y + 1)
  File &quot;unbound_local_error.py&quot;, line 7, in function_1
    a_1 = a_1 + a_2 + a
UnboundLocalError: local variable &#39;a_1&#39; referenced before assignment

Python exception:
    UnboundLocalError: local variable &#39;a_1&#39; referenced before assignment

Likely cause based on the information given by Python:
    The variable that appears to cause the problem is `a_1`.
    Perhaps the statement

        global a_1

    should have been included as the first line inside your function.
    The similar name `&#39;a_2&#39;` was found in the local scope.

Execution stopped on line 16 of file &#39;unbound_local_error.py&#39;.

   13: def function_3(x):
   14:     return 3 * function_2(x)
   15:
--&gt;16: function_3(1)

    Known identifiers:
        function_3: &lt;function function_3&gt;

Exception raised on line 7 of file &#39;unbound_local_error.py&#39;.

    4:
    5: def function_1(a):
    6:     a_2 = 4
--&gt; 7:     a_1 = a_1 + a_2 + a

    Known identifiers:
        global a_1: 2
        a_2: 4
        a: 2
</pre></div>
</div>
</div>
<div class="section" id="verbosity-level-6">
<h2>Verbosity level 6<a class="headerlink" href="#verbosity-level-6" title="Permalink to this headline">¶</a></h2>
<p>Same as level 4, with the addition of a Python traceback after
the rest of the information.</p>
<div class="highlight-none notranslate"><div class="highlight"><pre><span></span>Python exception:
    UnboundLocalError: local variable &#39;a_1&#39; referenced before assignment

Likely cause based on the information given by Python:
    The variable that appears to cause the problem is `a_1`.
    Perhaps the statement

        global a_1

    should have been included as the first line inside your function.
    The similar name `&#39;a_2&#39;` was found in the local scope.

Execution stopped on line 16 of file &#39;unbound_local_error.py&#39;.

   13: def function_3(x):
   14:     return 3 * function_2(x)
   15:
--&gt;16: function_3(1)

    Known identifiers:
        function_3: &lt;function function_3&gt;

Exception raised on line 7 of file &#39;unbound_local_error.py&#39;.

    4:
    5: def function_1(a):
    6:     a_2 = 4
--&gt; 7:     a_1 = a_1 + a_2 + a

    Known identifiers:
        global a_1: 2
        a_2: 4
        a: 2

Traceback (most recent call last):
  File &quot;unbound_local_error.py&quot;, line 16, in &lt;module&gt;
    function_3(1)
  File &quot;unbound_local_error.py&quot;, line 14, in function_3
    return 3 * function_2(x)
  File &quot;unbound_local_error.py&quot;, line 10, in function_2
    return function_1(y + 1)
  File &quot;unbound_local_error.py&quot;, line 7, in function_1
    a_1 = a_1 + a_2 + a
UnboundLocalError: local variable &#39;a_1&#39; referenced before assignment
</pre></div>
</div>
</div>
<div class="section" id="verbosity-level-7">
<h2>Verbosity level 7<a class="headerlink" href="#verbosity-level-7" title="Permalink to this headline">¶</a></h2>
<p>Same as level 4, except that some headers are not included.</p>
<div class="highlight-none notranslate"><div class="highlight"><pre><span></span>    UnboundLocalError: local variable &#39;a_1&#39; referenced before assignment

    The variable that appears to cause the problem is `a_1`.
    Perhaps the statement

        global a_1

    should have been included as the first line inside your function.
    The similar name `&#39;a_2&#39;` was found in the local scope.

   13: def function_3(x):
   14:     return 3 * function_2(x)
   15:
--&gt;16: function_3(1)

        function_3: &lt;function function_3&gt;

    4:
    5: def function_1(a):
    6:     a_2 = 4
--&gt; 7:     a_1 = a_1 + a_2 + a

        global a_1: 2
        a_2: 4
        a: 2
</pre></div>
</div>
</div>
<div class="section" id="verbosity-level-8">
<h2>Verbosity level 8<a class="headerlink" href="#verbosity-level-8" title="Permalink to this headline">¶</a></h2>
<p>Python traceback followed by a brief guess as to the likely cause.</p>
<div class="highlight-none notranslate"><div class="highlight"><pre><span></span>Traceback (most recent call last):
  File &quot;unbound_local_error.py&quot;, line 16, in &lt;module&gt;
    function_3(1)
  File &quot;unbound_local_error.py&quot;, line 14, in function_3
    return 3 * function_2(x)
  File &quot;unbound_local_error.py&quot;, line 10, in function_2
    return function_1(y + 1)
  File &quot;unbound_local_error.py&quot;, line 7, in function_1
    a_1 = a_1 + a_2 + a
UnboundLocalError: local variable &#39;a_1&#39; referenced before assignment

    The variable that appears to cause the problem is `a_1`.
    Perhaps the statement

        global a_1

    should have been included as the first line inside your function.
    The similar name `&#39;a_2&#39;` was found in the local scope.
</pre></div>
</div>
</div>
<div class="section" id="verbosity-level-9">
<h2>Verbosity level 9<a class="headerlink" href="#verbosity-level-9" title="Permalink to this headline">¶</a></h2>
<p>Only the Python traceback.</p>
<div class="highlight-none notranslate"><div class="highlight"><pre><span></span>Traceback (most recent call last):
  File &quot;unbound_local_error.py&quot;, line 16, in &lt;module&gt;
    function_3(1)
  File &quot;unbound_local_error.py&quot;, line 14, in function_3
    return 3 * function_2(x)
  File &quot;unbound_local_error.py&quot;, line 10, in function_2
    return function_1(y + 1)
  File &quot;unbound_local_error.py&quot;, line 7, in function_1
    a_1 = a_1 + a_2 + a
UnboundLocalError: local variable &#39;a_1&#39; referenced before assignment
</pre></div>
</div>
</div>
<div class="section" id="verbosity-level-0">
<h2>Verbosity level 0<a class="headerlink" href="#verbosity-level-0" title="Permalink to this headline">¶</a></h2>
<p>For all other levels that include a Python traceback, any calls
to Friendly-traceback itself are removed.  This shows the
true Python traceback, including the calls to our own code.
This is available for debugging purpose.</p>
<div class="highlight-none notranslate"><div class="highlight"><pre><span></span>Traceback (most recent call last):
  File &quot;c:\users\andre\github\friendly-traceback\friendly_traceback\editors_helper.py&quot;, line 141, in exec_code
    exec(code, module_globals)
  File &quot;unbound_local_error.py&quot;, line 16, in &lt;module&gt;
    function_3(1)
  File &quot;unbound_local_error.py&quot;, line 14, in function_3
    return 3 * function_2(x)
  File &quot;unbound_local_error.py&quot;, line 10, in function_2
    return function_1(y + 1)
  File &quot;unbound_local_error.py&quot;, line 7, in function_1
    a_1 = a_1 + a_2 + a
UnboundLocalError: local variable &#39;a_1&#39; referenced before assignment
</pre></div>
</div>
</div>
</div>


           </div>
           
          </div>
          <footer>
  

  <hr/>

  <div role="contentinfo">
    <p>
        
        &copy; Copyright 2019, André Roberge

    </p>
  </div>
    
    
    
    Built with <a href="http://sphinx-doc.org/">Sphinx</a> using a
    
    <a href="https://github.com/rtfd/sphinx_rtd_theme">theme</a>
    
    provided by <a href="https://readthedocs.org">Read the Docs</a>. 

</footer>

        </div>
      </div>

    </section>

  </div>
  

  <script type="text/javascript">
      jQuery(function () {
          SphinxRtdTheme.Navigation.enable(true);
      });
  </script>

  
  
    
   

</body>
</html>